input_type: pointcloud
input_resolution: 128
input_points_number: 100000
n_points_score: 100000
overlap_score_threshold: 0.3
model: SVR
action: geometry
dataset: GeometryDataset
refine_with_estimated_smpl: False
data:
  use_sdf: False
  use_smpl: False
  use_pose: False
trainer: GeometryTrainer
exp_name: SHARP2022_c1_t1_geometry
data_path: dataset/SHARP2022
data_bounding_box: [-0.8, 0.8, -0.15, 2.1, -0.8, 0.8]
split_file: dataset/SHARP2022/split_geometry.npz
preprocessing:
 color_sampling:
  input_files_regex: /*/*/*_normalized.obj
  sample_number: 100000
 geometry_sampling:
  input_files_regex: /*/*/*_normalized.obj
  sample_number: 100000
  sample_distribution: [0.5, 0.5]
  sample_sigmas: [0.015, 0.2]
 voxelized_pointcloud_sampling:
  input_files_regex: /*/*/*-partial-*.obj
 voxelized_colored_pointcloud_sampling:
  input_files_regex: /*/*/*-partial-*.obj

balanced_loss: False
reweighted_loss: False
focal_loss: False
training:
 batch_size: 2
 num_workers: 0
 sample_points_per_object: 50000
 optimizer: Adam
 lr: 0.0001
 loss:
  weight_near: 1
  weight_far: 1
generation:
 retrieval_resolution: 256
 checkpoint: -1
 batch_points: 800000
 mode: test
 retrieval_threshold: 0.5