input_type: pointcloud
input_resolution: 128
input_points_number: 100000
model: IFNetTexturePoseEncoding
action: texture
dataset: TextureDataset
trainer: TextureTrainer
exp_name: SHARP2022_c1_t1_texture
refine_with_estimated_smpl: true
data_path: ../dataset/SHARP2022/challenge1/track1/
data_bounding_box: [-0.8, 0.8, -0.15, 2.1, -0.8, 0.8]
split_file: ../dataset/SHARP2022/split_geometry.npz
overlap_score_threshold: 0.25
n_points_score: 100000
noise_sigmas: 0.01
preprocessing:
 color_sampling:
  input_files_regex: /*/*/*_normalized.obj
  sample_number: 100000
  sigma: 0.015
  ratio: 0.5
 geometry_sampling:
  input_files_regex: /*/*/*_normalized.obj
  sample_number: 100000
  sample_distribution: [0.5, 0.5]
  sample_sigmas: [0.015, 0.2]
 voxelized_pointcloud_sampling:
  input_files_regex: /*/*/*-partial*.obj
 voxelized_colored_pointcloud_sampling:
  input_files_regex: /train_partial/*/*-partial-*.obj
  sigma: 0.015

balanced_loss: false
reweighted_loss: false
training:
 batch_size: 1
 num_workers: 0
 sample_points_per_object: 50000
 optimizer: Adam
 scheduler: true
 lr: 0.0001
 loss:
  weight_near: 1
  weight_far: 1
generation:
 retrieval_resolution: 256
 checkpoint: -1
 batch_points: 800000
 mode: test
 retrieval_threshold: 0.5